[package]
name = "predicat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nom = "7.1.1"
polars = "0.26.1"
regex = "1.8.1"
sqlite = "0.30.3"
