[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
regex = "1.8.1"
itertools = "0.10.5"
base_context = { path = "../base_context" } 
