@startuml
scale 10

object interfaces {
	shell
	cli
	server
}

object importers {
	 csv_importer
	 json_importer
	 predicat_importer
}

object controllers {
	data_conformity	
	compliance
}

object knowledge {
	 facts
}

object inference_engines {
	 rules
	 IA
	 machine_learning
}

object exporters {
	 json_exporter
	 csv_exporter	
	 custom_exporter
}

interfaces -down-> importers : use
interfaces -> controllers : manage
interfaces -> inference_engines : manage
interfaces -down-> exporters : use
importers -> controllers : convert and import
controllers -> inference_engines : add
inference_engines -> knowledge : update
knowledge -> exporters : convert and export
@enduml
